### ISSUE TITLE
How do in install it

### ISSUE THREAD

**Issue by legendmt25** [azman/my1sim85#2]
There is no extension to INSTALL file its the same with the other files too, and can i install it on windows 10 or do i need to use something like virtual box?
Can you tell me please?
Its for my1sim85

**Comment by azman** [comment]
> There is no extension to INSTALL file its the same with the other files too, and can i install it on windows 10 or do i need to use something like virtual box?
> Can you tell me please?
> Its for my1sim85

This is a source code repository - that INSTALL file is a text file containing information on how to build the program from source (and install/use it). If you are on windows, go to releases page and download the latest version (at the moment, it is 0.9.0) - which is in zip form. Simply unzip to a path (preferably, one without any white space in its full name), an run.
